### ISSUE TITLE
How to determine whether or not a tcp packet is ss traffic according to its entropy? And why this?

### ISSUE THREAD

**Issue by lonnyzhang423** [isofew/sssniff#1]
```python
if tcp.flags & dpkt.tcp.TH_PUSH != 0:
		track[c].append((entropy(dist(str(tcp.payload))), s))
		if len(track[c]) >= 4:
			if track[c][0][0] > 4.8 or \
			   (track[c][0][0] > 4.4 and track[c][1][0] > 4.2) or \
			   (track[c][0][0] > 4.2 and track[c][2][0] > 4.2 and \
				track[c][0][1] == track[c][2][1]) or \
			   track[c][0][1] == track[c][1][1]:
				add(c, 1)
			else:
				add(c, -1)
			del track[c]
```

**Comment by isofew** [comment]
SS traffic has no plaintext sections, so its payloads are essentially a pseudo-random stream and can be identified with a high entropy.

The code snippet you posted is some hand-crafted thresholds which I couldn't recall how I got them; nevertheless, this approach is too compute-intensive to be deployed in a real network scenario anyway.

If you are interested in network traffic classification and obfuscation, go check some machine learning approaches and try write a GAN to deceive the classifier ;)

**Comment by lonnyzhang423** [comment]
Can I make out in this way,any encrypted data with a high entropy will be identified as SS traffic according to your code,no matter what cryptography method and protocal we use?

**Comment by isofew** [comment]
@lonnyzhang423 Partly. Any connection that has no plaintext at the _beginning_ will be identified.

**Comment by lonnyzhang423** [comment]
@isofew Get it!Thanks!
