### ISSUE TITLE
是否是真正的识别了SS流量？

### ISSUE THREAD

**Issue by RainJoe** [isofew/sssniff#2]
请问这个能识别混淆了的TCP流量吗？还是说只是识别了SOCKS5协议的流量？

**Comment by isofew** [comment]
加HTTP头应该可以通过这个（原始版的）检测，如果是基于包长度的混淆可能不太管用。我一年多没关注这方面话题了，你可以参考下这个项目的其他fork。
没有什么绝对的“真正识别”或者“完全混淆”，还是根据自己的使用环境决定用哪种混淆方法（或者不用）最适合吧。
